export const FETCHING_PROFILE_REQUESTED = 'auth/FETCHING_PROFILE_REQUESTED'
export const FETCHING_PROFILE_LOADING = 'auth/FETCHING_PROFILE_LOADING'
export const FETCHING_PROFILE_SUCCESS = 'auth/FETCHING_PROFILE_SUCCESS'
export const FETCHING_PROFILE_FAILURE = 'auth/FETCHING_PROFILE_FAILURE'
