export const FETCHING_PROFILE_REQUESTED = 'auth/FETCHING_PROFILE_REQUESTED'
export const FETCHING_PROFILE_LOADING = 'auth/FETCHING_PROFILE_LOADING'
export const FETCHING_PROFILE_SUCCESS = 'auth/FETCHING_PROFILE_SUCCESS'
export const FETCHING_PROFILE_FAILURE = 'auth/FETCHING_PROFILE_FAILURE'

export const FETCHING_PHRASES_BY_ME_REQUESTED = 'auth/FETCHING_PHRASES_BY_ME_REQUESTED'
export const FETCHING_PHRASES_BY_ME_LOADING = 'auth/FETCHING_PHRASES_BY_ME_LOADING'
export const FETCHING_PHRASES_BY_ME_SUCCESS = 'auth/FETCHING_PHRASES_BY_ME_SUCCESS'
export const FETCHING_PHRASES_BY_ME_FAILURE = 'auth/FETCHING_PHRASES_BY_ME_FAILURE'
