export const FETCHING_CONVERSATION_LIST_REQUEST =
  'conversation/FETCHING_CONVERSATION_LIST_REQUEST';
export const FETCHING_CONVERSATION_LIST_FAILURE =
  'conversation/FETCHING_CONVERSATION_LIST_FAILURE';
export const FETCHING_CONVERSATION_LIST_SUCCESS =
  'conversation/FETCHING_CONVERSATION_LIST_SUCCESS';

export const FETCHING_MESSAGE_REQUEST = 'conversation/FETCHING_MESSAGE_REQUEST';
export const FETCHING_MESSAGE_FAILURE = 'conversation/FETCHING_MESSAGE_FAILURE';
export const FETCHING_MESSAGE_SUCCESS = 'conversation/FETCHING_MESSAGE_SUCCESS';
export const RESET_FETCHING_MESSAGE = 'conversation/RESET_FETCHING_MESSAGE';

export const SENDING_MESSAGE_REQUEST = 'conversation/SENDING_MESSAGE_REQUEST';
export const SENDING_MESSAGE_FAILURE = 'conversation/SENDING_MESSAGE_FAILURE';
export const SENDING_MESSAGE_SUCCESS = 'conversation/SENDING_MESSAGE_SUCCESS';

export const MERGE_MESSAGE = 'conversation/MERGE_MESSAGE';

export const SET_USER_TO_START_CHATTING =
  'conversation/SET_USER_TO_START_CHATTING';
export const UNSET_USER_TO_START_CHATTING =
  'conversation/UNSET_USER_TO_START_CHATTING';

export const SENDING_FIRST_MESSAGE_REQUEST =
  'conversation/SENDING_FIRST_MESSAGE_REQUEST';
export const SENDING_FIRST_MESSAGE_FAILURE =
  'conversation/SENDING_FIRST_MESSAGE_FAILURE';
export const SENDING_FIRST_MESSAGE_SUCCESS =
  'conversation/SENDING_FIRST_MESSAGE_SUCCESS';
export const RESET_SEND_FIRST_MESSAGE = 'conversation/RESET_SEND_FIRST_MESSAGE';

export const CREATE_CONVERSATION_REQUEST =
  'conversation/CREATE_CONVERSATION_REQUEST';
export const CREATE_CONVERSATION_FAILURE =
  'conversation/CREATE_CONVERSATION_FAILURE';
export const CREATE_CONVERSATION_SUCCESS =
  'conversation/CREATE_CONVERSATION_SUCCESS';
