export const CREATE_PHRASE_REQUEST = 'phrasebook/CREATE_PHRASE_REQUEST';
export const CREATE_PHRASE_FAILURE = 'phrasebook/CREATE_PHRASE_FAILURE';
export const CREATE_PHRASE_SUCCESS = 'phrasebook/CREATE_PHRASE_SUCCESS';
export const RESET_CREATE_PHRASE_STATE = 'phrasebook/RESET_CREATE_PHRASE_STATE';

export const FETCHING_PHRASEBOOKS_REQUEST =
  'phrasebook/FETCHING_PHRASEBOOKS_REQUEST';
export const FETCHING_PHRASEBOOKS_FAILURE =
  'phrasebook/FETCHING_PHRASEBOOKS_FAILURE';
export const FETCHING_PHRASEBOOKS_SUCCESS =
  'phrasebook/FETCHING_PHRASEBOOKS_SUCCESS';
export const RESET_FETCHING_PHRASEBOOKS_STATE =
  'phrasebook/RESET_FETCHING_PHRASEBOOKS_STATE';

export const FETCHING_LATEST_PHRASEBOOK_REQUEST =
  'phrasebook/FETCHING_LATEST_PHRASEBOOK_REQUEST';
export const FETCHING_LATEST_PHRASEBOOK_FAILURE =
  'phrasebook/FETCHING_LATEST_PHRASEBOOK_FAILURE';
export const FETCHING_LATEST_PHRASEBOOK_SUCCESS =
  'phrasebook/FETCHING_LATEST_PHRASEBOOK_SUCCESS';
