export const OPEN_DIALOG_PHRASEBOOK_DETAILS =
  'common/OPEN_DIALOG_PHRASEBOOK_DETAILS';
export const CLOSE_DIALOG_PHRASEBOOK_DETAILS =
  'common/CLOSE_DIALOG_PHRASEBOOK_DETAILS';
export const TOGGLE_DIALOG_PHRASEBOOK_DETAILS =
  'common/TOGGLE_DIALOG_PHRASEBOOK_DETAILS';

export const OPEN_DRAWER = 'common/OPEN_DRAWER';
export const CLOSE_DRAWER = 'common/CLOSE_DRAWER';
export const TOGGLE_DRAWER = 'common/TOGGLE_DRAWER';

export const OPEN_DIALOG_CONFIRM_LOGOUT = 'common/OPEN_DIALOG_CONFIRM_LOGOUT';
export const CLOSE_DIALOG_CONFIRM_LOGOUT = 'common/CLOSE_DIALOG_CONFIRM_LOGOUT';
