/** Actions types  */
export const FETCHING_PROFILE_REQUEST = 'account/FETCHING_PROFILE_REQUEST';
export const FETCHING_PROFILE_FAILURE = 'account/FETCHING_PROFILE_FAILURE';
export const FETCHING_PROFILE_SUCCESS = 'account/FETCHING_PROFILE_SUCCESS';
