/** Actions types  */
export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
// export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const FETCHING_AUTHENTICATED_USER_REQUEST =
  'auth/FETCHING_AUTHENTICATED_USER_REQUEST';
export const FETCHING_AUTHENTICATED_USER_FAILURE =
  'auth/FETCHING_AUTHENTICATED_USER_FAILURE';
export const FETCHING_AUTHENTICATED_USER_SUCCESS =
  'auth/FETCHING_AUTHENTICATED_USER_SUCCESS';

export const REVOKING_TOKEN_REQUEST = 'auth/REVOKING_TOKEN_REQUEST';
export const REVOKING_TOKEN_FAILURE = 'auth/REVOKING_TOKEN_FAILURE';
export const REVOKING_TOKEN_SUCCESS = 'auth/REVOKING_TOKEN_SUCCESS';

export const RESET_AUTH_STATE = 'auth/RESET_AUTH_STATE';
