export const CREATE_DISCUSSION_REQUEST = 'phrasebook/CREATE_DISCUSSION_REQUEST';
export const CREATE_DISCUSSION_FAILURE = 'phrasebook/CREATE_DISCUSSION_FAILURE';
export const CREATE_DISCUSSION_SUCCESS = 'phrasebook/CREATE_DISCUSSION_SUCCESS';
export const RESET_CREATE_DISCUSSION_STATE =
  'phrasebook/RESET_CREATE_DISCUSSION_STATE';

export const FETCHING_DISCUSSION_LIST_REQUEST =
  'phrasebook/FETCHING_DISCUSSION_LIST_REQUEST';
export const FETCHING_DISCUSSION_LIST_FAILURE =
  'phrasebook/FETCHING_DISCUSSION_LIST_FAILURE';
export const FETCHING_DISCUSSION_LIST_SUCCESS =
  'phrasebook/FETCHING_DISCUSSION_LIST_SUCCESS';
