export const LOGIN_REQUESTED = 'auth/LOGIN_REQUESTED'
export const LOGIN_LOADING = 'auth/LOGIN_LOADING'
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE'

export const REGISTER_REQUESTED = 'auth/REGISTER_REQUESTED'
export const REGISTER_LOADING = 'auth/REGISTER_LOADING'
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE'
