export const ROUTES = {
  PREFIX: '/app',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  LOGGEDOUT: '/logged-out',
  PHRASEBOOK_LIST: '/phrasebook',
  CHAT: '/chat',
  SETTINGS: '/settings',
  FAVORITE: '/favorite',
  THREAD: '/thread',
  PROFILE: '/profile',
  CONTACT: '/contact',
  ABOUT: '/about',
  NOT_MATCH: '/404',
};
