export const FETCHING_USER_LIST_REQUEST = 'user/FETCHING_USER_LIST_REQUEST';
export const FETCHING_USER_LIST_FAILURE = 'user/FETCHING_USER_LIST_FAILURE';
export const FETCHING_USER_LIST_SUCCESS = 'user/FETCHING_USER_LIST_SUCCESS';
