export const FETCHING_PHRASEBOOK_CATEGORIES_REQUEST =
  'category/FETCHING_PHRASEBOOK_CATEGORIES_REQUEST';
export const FETCHING_PHRASEBOOK_CATEGORIES_FAILURE =
  'category/FETCHING_PHRASEBOOK_CATEGORIES_FAILURE';
export const FETCHING_PHRASEBOOK_CATEGORIES_SUCCESS =
  'category/FETCHING_PHRASEBOOK_CATEGORIES_SUCCESS';

export const SET_CURRENT_CATEGORY_TAB = 'category/SET_CURRENT_CATEGORY_TAB';
export const UNSET_CURRENT_CATEGORY_TAB = 'category/UNSET_CURRENT_CATEGORY_TAB';
