export const FETCHING_PHRASEBOOK_REQUESTED = 'phrasebook/FETCHING_PHRASEBOOK_REQUESTED'
export const FETCHING_PHRASEBOOK_LOADING = 'phrasebook/FETCHING_PHRASEBOOK_LOADING'
export const FETCHING_PHRASEBOOK_FAILURE = 'phrasebook/FETCHING_PHRASEBOOK_FAILURE'
export const FETCHING_PHRASEBOOK_SUCCESS = 'phrasebook/FETCHING_PHRASEBOOK_SUCCESS'
export const UPDATE_PHRASE_ITEM = 'phrasebook/UPDATE_PHRASE_ITEM'

export const SET_DRAWER_ADD_EDIT_PHRASE = 'phrasebook/SET_DRAWER_ADD_EDIT_PHRASE'

export const CREATE_PHRASE_REQUESTED = 'phrasebook/CREATE_PHRASE_REQUESTED'
export const CREATE_PHRASE_LOADING = 'phrasebook/CREATE_PHRASE_LOADING'
export const CREATE_PHRASE_FAILURE = 'phrasebook/CREATE_PHRASE_FAILURE'
export const CREATE_PHRASE_SUCCESS = 'phrasebook/CREATE_PHRASE_SUCCESS'

export const UPDATE_PHRASE_REQUESTED = 'phrasebook/UPDATE_PHRASE_REQUESTED'
export const UPDATE_PHRASE_LOADING = 'phrasebook/UPDATE_PHRASE_LOADING'
export const UPDATE_PHRASE_FAILURE = 'phrasebook/UPDATE_PHRASE_FAILURE'
export const UPDATE_PHRASE_SUCCESS = 'phrasebook/UPDATE_PHRASE_SUCCESS'

export const FETCHING_PHRASE_BY_ID_REQUESTED = 'phrasebook/FETCHING_PHRASE_BY_ID_REQUESTED'
export const FETCHING_PHRASE_BY_ID_LOADING = 'phrasebook/FETCHING_PHRASE_BY_ID_LOADING'
export const FETCHING_PHRASE_BY_ID_FAILURE = 'phrasebook/FETCHING_PHRASE_BY_ID_FAILURE'
export const FETCHING_PHRASE_BY_ID_SUCCESS = 'phrasebook/FETCHING_PHRASE_BY_ID_SUCCESS'
